Hello: Welcome to ssdesk
HelloDescription: [insert description here]
Go: Go!
NavAll: View all
Logout: Logout
Login: Login
Register: Register
Search: Search
RegisterNote: Your account must be validated by an admin. This usually happens within 24 hours.
BoardStartThread: Start new thread
BoardReplyThread: Replying to thread
MediaDescription: anime & music
MediaType: Type
MediaFilename: Filename
MediaSize: Size
MediaModified: Modified
