Hello: Welcome to ssdesk
HelloDescription: [insert description here]
Go: Go!
NavAll: View all
Logout: Logout
Login: Login
Register: Register
Search: Search
RegisterNote: New accounts must be approved by an admin. Identify yourself in the comment box!
BoardStartThread: Start new thread
BoardReplyThread: Replying to thread
MediaDescription: anime & music
MediaType: Type
MediaFilename: Filename
MediaSize: Size
MediaModified: Modified
LabelImportant: Important!
