Hello: Welcome to ssdesk
HelloDescription: [insert description here]

ByTags: Tags
ByDate: Archives

Login:      Login

Logout:     Logout
LoggedOut:  You are now logged out

Register:         Registration
RegisterAction:   Register
RegisterNote:     Only those linked to PVL can have their account verified.

NavAll: View all

AdminSpace: Admin tools

Search: Search

BoardCreate:      Create
BoardStartThread: Start new thread
BoardReplyThread: Replying to thread

MediaDescription: anime & music
MediaActions:     Media section actions
MediaType:     Type
MediaFilename: Filename
MediaSize:     Size
MediaModified: Modified

LabelImportant: Note

PostPublish:   Publish a new post
PostEdit:      Edit post
PostComment:   Leave a comment
PostActionPublish:   Publish
PostActionComment:   Comment
PostCommentsNone: No comments
PostCommentsOne:  One comment
PostCommentsN:    Comments

FormOneError: An error was encountered. Please, fix it.
FormNErrors:  Errors were encountered. Please, fix them.
FormSuccess:  Form was succesfully submitted.

Unknown: This text message has no value set!
