Default: &defaults
  user: rnfssp
  password: <password>
  host: localhost
  port: 5432
  database: rnfssp
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: rnfssp_test
  <<: *defaults

Staging:
  database: rnfssp_staging
  poolsize: 100
  <<: *defaults

Production:
  database: rnfssp_production
  poolsize: 100
  <<: *defaults
