Default: &defaults
  host: "localhost"
  port: 3001
  copyright: "BPS"
  #analytics: UA-YOURCODE
  animedir: "/home/sim/anime"
  musicdir: "/home/sim/music"

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  host: "*4"
  port: 3000
  approot: "https://ssdesk.paivola.fi"
  animedir: "/home/media/anime"
  musicdir: "/home/media/music"
  <<: *defaults
