Default: &defaults
  host:      "*4"
  port:      3000
  approot:   "http://localhost:3000"
  serveroot: "http://localhost:3000"
  copyright: "BPS"
  dyndir:    "/home/sim/rnfssp/files"
  mediasections:
    anime:
      view: "Anime"
      type: "film"
      icon: "film"
      path: "/other/sim/anime"
    music:
      view: "Music"
      type: "mpd"
      icon: "music"
      path: "/other/sim/music"

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  host:      "*4"
  port:      3001
  approot:   "https://ssdesk.paivola.fi"
  serveroot: "http://ssdesk.paivola.fi"
  dyndir:    "/srv/sites/rnfssp/files"
  mediasections:
    anime:
      view: "Anime"
      type: "film"
      icon: "film"
      path: "/home/media/anime"
    music:
      view: "Music"
      type: "mpd"
      icon: "music"
      path: "/home/media/music"
    hentai:
      view: "Hentai"
      type: "film"
      icon: "film"
      path: "/home/media/hentai"
    games:
      view: "Games"
      type: "film"
      icon: "headphones"
      path: "/home/media/game"
    movies:
      view: "Movies"
      type: "film"
      icon: "film"
      path: "/home/media/movie"
    books:
      view: "Books"
      type: "film"
      icon: "book"
      path: "/home/media/books"
    series:
      view: "Series"
      type: "film"
      icon: "film"
      path: "/home/media/series"
    images:
      view: "Images"
      type: "film"
      icon: "picture"
      path: "/home/media/images"
  <<: *defaults

