Default: &defaults
  host:      "*4"
  port:      3001
  approot:   "http://localhost:3001"
  serveroot: "http://localhost:3001"
  copyright: "BPS"
  #analytics: UA-YOURCODE
  animedir:  "/home/sim/anime"
  musicdir:  "/home/sim/music"
  dyndir:    "/home/sim/rnfssp/files"

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  host:      "*4"
  port:      3000
  approot:   "https://ssdesk.paivola.fi"
  serveroot: "http://ssdesk.paivola.fi"
  animedir:  "/home/media/anime"
  musicdir:  "/home/media/music"
  dyndir:    "/srv/sites/rnfssp/files"
  <<: *defaults
